baseURL = 'https://diegor2.github.io/ateu.info/'
languageCode = 'pt-BR'
title = 'ateu.info'
theme = ['hugo-video', 'hugo-theme-stack']

[params]
mainSections = 'posts'
featuredImageField = 'featured_image'

[params.sidebar]
emoji = 'ğŸ¸'
subtitle = 'Arquivo Ateuinforma'

[params.sidebar.avatar]
enabled = 'false'

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

[opengraph.twitter]
site = ""
card = "summary_large_image"


[markup.goldmark.renderer]
hardWraps = true
